// Generated by https://quicktype.io

export type QuestsUser =  {
    id:           number;
    end_at:       null | string;
    quest_id:     number;
    validated_at: null | string;
    prct:         null | string;
    advancement:  null |string;
    created_at:   string;
    updated_at:   string;
    user:         {
        id:    number;
        login: string;
        url:   string;
    };
    quest:        {
        id:            number;
        name:          string;
        slug:          string;
        kind:          string;
        internal_name: null | string;
        description:   string;
        cursus_id:     number;
        campus_id:     null | string;
        created_at:    string;
        updated_at:    string;
        grade_id:      null |string;
        position:      number;
    };
}

