// Generated by https://quicktype.io

export type Attachment = {
    id:             number,
    name:           string,
    pdf:            {
        pdf: {
            url:   null
            thumb: {
                url: null,
            },
        },
    },
    page_count:     number,
    created_at:     string,
    pdf_processing: boolean,
    slug:           string,
    url:            null,
    thumb_url:      null,
    base_id:        number,
    language:       {
        id:         number;
        name:       string;
        identifier: string;
    },
    type:           string,
}

