// Generated by https://quicktype.io

export type ProjectSession = {
    id:                     number,
    solo:                   boolean,
    begin_at:               null,
    end_at:                 null,
    estimate_time:          string,
    difficulty:             number,
    objectives:             string[],
    description:            string,
    duration_days:          null,
    terminating_after:      null,
    project_id:             number,
    campus_id:              number,
    cursus_id:              number,
    created_at:             string,
    updated_at:             string,
    max_people:             null,
    is_subscriptable:       boolean,
    scales:                 {
        id:                number,
        correction_number: number,
        is_primary:        boolean,
    }[];
    uploads:                {
        id:   number;
        name: string;
    }[],
    team_behaviour:         string;
    commit:                 null;
    project:                {
        id:          number;
        name:        string;
        slug:        string;
        difficulty:  number;
        parent:      null;
        children:    any[];
        attachments: any[];
        created_at:  string;
        updated_at:  string;
        exam:        boolean;
        git_id:      null;
        repository:  null;
    };
    campus:                 {
        id:                   number;
       name:                 string;
        time_zone:            string;
        language:             {
            id:         number;
            name:       string;
            identifier: string;
            created_at: string;
            updated_at: string;
        };
        users_count:          number;
        vogsphere_id:         number;
        country:              string;
        address:              string;
        zip:                  string;
        city:                 string;
        website:              string;
        facebook:             string;
        twitter:              string;
        active:               boolean;
        public:               boolean;
        email_extension:      string;
        default_hidden_phone: boolean;
    };
    cursus:                 {
        id:         number;
        created_at: string;
        name:       string;
        slug:       string;
        kind:       string;
    };
    evaluations:            {
        id:   number;
        kind: string;
    }[];
    project_sessions_rules: {
        id:       number;
        required: boolean;
        position: number;
        params:   {
            id:                       number;
            param_id:                 number;
            project_sessions_rule_id: number;
            value:                    string;
            created_at:               string;
            updated_at:               string;
        }[];
        rule:     {
            id:            number;
            kind:          string;
            name:          string;
            description:   string;
            created_at:    string;
            updated_at:    string;
            slug:          string;
            internal_name: string;
        };
    }[];
}

