export type CommunityServicesParams = {
	sort?: "id" | "close_id" | "tiger_id" | "duration" | "schedule_at" | 'occupation'  | 'token' | "state" |"created_at" | "updated_at",
	"filter[id]"?: number[],
	"filter[close_id]"?: string[],
	"filter[tiger_id]"?: string[],
	"filter[duration]"?: string[],
	"filter[schedule_at]"?: string[],
	"filter[occupation]"?: number[],
	"filter[token]"?: string[],
	"filter[state]"?: string[],
	"filter[created_at]"?: string[],
	"filter[updated_at]"?: string[],
	"range[id]"?: string,
	"range[coalition_id]"?: string,
	"range[user_id]"?: string,
	"range[created_at]"?: string,
	"range[updated_at]"?: string,
	"range[this_year_score]"?: string,
	"range[this_year_score_updated_at]"?: string,
	page?: number,
	"page[number]"?: number,
	"page[size]"?: number,
}