export type UsersParams = {
  cursus_id?: string;
  tag_id?: string;
  field?: "created_at" | "updated_at";
  interval?:
    | "day"
    | "week"
    | "month"
    | "quarter"
    | "year"
    | "hour_of_day"
    | "day_of_week"
    | "day_of_month"
    | "month_of_year";
  sort?:
    | "id"
    | "login"
    | "email"
    | "encrypted_password"
    | "reset_password_token"
    | "reset_password_sent_at"
    | "created_at"
    | "updated_at"
    | "image"
    | "first_name"
    | "last_name"
    | "pool_year"
    | "pool_month"
    | "kind"
    | "status"
    | "otp_secret_key"
    | "otp_tmp"
    | "otp_activated"
    | "otp_backup_passwords"
    | "slack_team"
    | "slack_login"
    | "slack_mail"
    | "slack_code_validation"
    | "slack_validated_at"
    | "token_id"
    | "email_stop"
    | "linked_user_id"
    | "usual_first_name"
    | "last_seen_at"
    | "password_changed_at"
    | "encrypted_single_usage_password"
    | "first_warn_anon_sent_at"
    | "second_warn_anon_sent_at"
    | "alumnized_at";
  "filter[id]": string[];
  "filter[login]": string[];
  "filter[email]": string[];
  "filter[created_at]": string[];
  "filter[updated_at]": string[];
  "filter[pool_year]": string[];
  "filter[pool_month]": string[];
  "filter[kind]": string[];
  "filter[status]": string[];
  "filter[primary_campus_id]": string[];
  "filter[first_name]": string[];
  "filter[last_name]": string[];
  "filter[alumni?]": string[];
  "filter[staff?]": string[];
  "range[id]": string[];
  "range[login]": string[];
  "range[email]": string[];
  "range[created_at]": string[];
  "range[updated_at]": string[];
  "range[pool_year]": string[];
  "range[pool_month]": string[];
  "range[kind]": string[];
  "range[status]": string[];
  page?: number;
  "page[number]"?: number;
  "page[size]"?: number;
};

export type UsersParams2 = {
  coalition_id?: string;
  dash_id?: string;
  event_id?: string;
  accreditation_id?: string;
  team_id?: string;
  project_id?: string;
  partnership_id?: string;
  expertise_id?: string;
  cursus_id?: string;
  campus_id?: string;
  achievement_id?: string;
  title_id?: string;
  quest_id?: string;
  group_id?: string;
  sort?:
    | "id"
    | "login"
    | "email"
    | "encrypted_password"
    | "reset_password_token"
    | "reset_password_sent_at"
    | "created_at"
    | "updated_at"
    | "image"
    | "first_name"
    | "last_name"
    | "pool_year"
    | "pool_month"
    | "kind"
    | "status"
    | "otp_secret_key"
    | "otp_tmp"
    | "otp_activated"
    | "otp_backup_passwords"
    | "slack_team"
    | "slack_login"
    | "slack_mail"
    | "slack_code_validation"
    | "slack_validated_at"
    | "token_id"
    | "email_stop"
    | "linked_user_id"
    | "usual_first_name"
    | "last_seen_at"
    | "password_changed_at"
    | "encrypted_single_usage_password"
    | "first_warn_anon_sent_at"
    | "second_warn_anon_sent_at"
    | "alumnized_at";
  "filter[id]": string[];
  "filter[login]": string[];
  "filter[email]": string[];
  "filter[created_at]": string[];
  "filter[updated_at]": string[];
  "filter[pool_year]": string[];
  "filter[pool_month]": string[];
  "filter[kind]": string[];
  "filter[status]": string[];
  "filter[primary_campus_id]": string[];
  "filter[first_name]": string[];
  "filter[last_name]": string[];
  "filter[alumni?]": string[];
  "filter[staff?]": string[];
  "range[id]": string[];
  "range[login]": string[];
  "range[email]": string[];
  "range[created_at]": string[];
  "range[updated_at]": string[];
  "range[pool_year]": string[];
  "range[pool_month]": string[];
  "range[kind]": string[];
  "range[status]": string[];
};
