export type OffersParams = {
  sort?:
    | "id"
    | "title"
    | "little_description"
    | "big_description"
    | "salary"
    | "contract_type"
    | "email"
    | "address"
    | "city"
    | "zip"
    | "country"
    | "latitude"
    | "longitude"
    | "valid_at"
    | "invalid_at"
    | "min_duration"
    | "max_duration"
    | "document"
    | "slug"
    | "created_at"
    | "updated_at"
    | "pro_id"
    | "company_id"
    | "target";
  "filter[id]"?: number[];
  "filter[title]": string[];
  "filter[little_description]": string[];
  "filter[big_description]": string[];
  "filter[salary]": string[];
  "filter[contract_type]": string[];
  "filter[email]": string[];
  "filter[address]": string[];
  "filter[city]": string[];
  "filter[zip]": string[];
  "filter[country]": string[];
  "filter[latitude]": string[];
  "filter[longitude]": string[];
  "filter[valid_at]": string[];
  "filter[invalid_at]": string[];
  "filter[min_duration]": string[];
  "filter[max_duration]": string[];
  "filter[document]": string[];
  "filter[slug]": string[];
  "filter[created_at]"?: number[];
  "filter[updated_at]"?: string[];
  "filter[pro_id]": string[];
  "filter[company_id]": string[];
  "filter[target]": string[];
  "filter[expertise_id]": string[];
  "filter[campus_id]": string[];
  "filter[expertise]": string[];
  "filter[reported]": string[];
  "filter[user_id]": string[];
  "filter[valid]": string[];
  "filter[invalid]": string[];
  page?: number;
  "page[number]"?: number;
  "page[size]"?: number;
};
