export type TeamsParams = {
    cursus_id?:            string | number,
    user_id?:           string | number,
    project_id?:           string | number,
    project_session_id?:           string | number,
    sort?:               "id" | "project_id" | "name" | "created_at" | "updated_at" | "locked_at" | "closed_at" | "final_mark" | "repo_url" | "repo_uuid" | "deadline_at" | "terminating_at" | "project_session_id" | "status",


    
    "filter[id]"?:string[] | number[],
    "filter[project_id]"?:string[],
    "filter[name]"?:string[],
    "filter[created_at]"?:string[],
    "filter[updated_at]"?:string[],
    "filter[locked_at]"?:string[],
    "filter[closed_at]"?:string[],
    "filter[final_mark]"?:string[],
    "filter[repo_url]"?:string[],
    "filter[repo_uuid]"?:string[],
    "filter[deadline_at]"?:string[],
    "filter[terminating_at]"?:string[],
    "filter[project_session_id]"?:string[],
    "filter[status]"?:string[],
    "filter[cursus]"?:string[],
    "filter[active_cursus]"?:string[],
    "filter[campus]"?:string[],
    "filter[primary_campus]"?:string[],
    "filter[locked]"?:string[],
    "filter[closed]"?:string[],
    "filter[deadline]"?:string[],
    "filter[terminating]"?:string[],
    "filter[with_mark]"?:string[],
  
    "range[id]"?:string[] ,
    "range[project_id]"?:string[] ,
    "range[name]"?:string[],
    "range[created_at]"?:string[],
    "range[updated_at]"?:string[],
    "range[locked_at]"?:string[] ,
    "range[closed_at]"?:string[] ,
    "range[final_mark]"?:string[] ,
    "range[repo_url]"?:string[] ,
    "range[repo_uuid]"?:string[] ,
    "range[deadline_at]"?:string[] ,
    "range[terminating_at]"?:string[] ,
    "range[project_session_id]"?:string[] ,
    "range[status]"?:string[] ,

    page?:                          number,
    "page[number]"?:                number,
    "page[size]"?:                  number,

}
