// Generated by https://quicktype.io

export type Announcement = {
    id:         number;
    author:     string;
    title:      string;
    text:       string;
    kind:       string;
    link:       null;
    created_at: string;
    updated_at: string;
    expire_at:  string;
}
