// Generated by https://quicktype.io

export type Project = {
    id:               number,
    name:             string,
    slug:             string,
    difficulty:       number,
    description:      string,
    parent:           null,
    children:         any[],
    objectives:       string[],
    attachments:      any[],
    created_at:       string,
    updated_at:       string,
    exam:             boolean,
    cursus:           {
        id:         number,
        created_at: string,
        name:       string,
        slug:       string,
    }[];
    campus:           {
        id:           number,
        name:         string,
        time_zone:    string,
        language:     {
            id:         number;
            name:       string;
            identifier: string;
            created_at: string;
            updated_at: string;
        },
        users_count:  number,
        vogsphere_id: number,
    }[];
    skills:           {
        id:         number,
        created_at: string,
        name:       string,
    }[];
    videos:           any[];
    tags:             {
        id:   number,
        name: string,
        kind: string,
    }[];
    project_sessions: {
        id:                number,
        solo:              boolean,
        begin_at:          null,
        end_at:            null,
        difficulty:        number,
        estimate_time:     number,
        duration_days:     null,
        terminating_after: null,
        project_id:        number,
        campus_id:         null,
        cursus_id:         null,
        created_at:        string,
        updated_at:        string,
        max_people:        null,
        is_subscriptable:  boolean,
        scales:            {
            id:                number;
            correction_number: number;
            is_primary:        boolean;
        }[],
        uploads:           {
            id:   number;
            name: string;
        }[],
        team_behaviour:    string,
    }[];
}
