// Generated by https://quicktype.io

export type ProjectSessionsSkill = {
    id:                 number,
    project_session_id: number,
    skill_id:           number,
    value:              number,
    created_at:         string,
    updated_at:         string,
}
