// Generated by https://quicktype.io

export type AchievementsUser = {
    id:                 number;
    achievement_id:     number,
    user_id:            number;
    login:              string;
    nbr_of_success:     number;
    url:                string;
    created_at:         string;
    updated_at:         string
}
