// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export type Coalition = {
  id: number | string;
  name: string;
  slug: string;
  image_url: string;
  color: string;
  score: number;
  user_id: number | string;
}
