// Generated by https://quicktype.io

export type Bloc = {
    id:         number,
    campus_id:  number,
    cursus_id:  number,
    squad_size: number,
    created_at: string,
    updated_at: string,
    coalitions: {
        id:        number,
        name:      string,
        slug:      string,
        image_url: string,
        color:     string,
        score:     number,
        user_id:   number,
    }[],
}

