// Generated by https://quicktype.io

export type Campus = {
    id:                   number;
    name:                 string,
    time_zone:            string,
    language:             {
        id:         number,
        name:       string,
        identifier: string,
    },
    users_count:          number,
    vogsphere_id:         number,
    country:              string,
    address:              string,
    zip:                  string,
    city:                 string,
    website:              string,
    facebook:             string,
    twitter:              string,
    active:               boolean,
    public:               boolean,
    email_extension:      string,
    default_hidden_phone: boolean,
    endpoint:             {
        id:          number,
        url:         string,
        description: string,
        created_at:  string,
        updated_at:  string,
    }
}

