// Generated by https://quicktype.io

export type Achievement = {
    id:             number;
    name:           string;
    description:    string;
    tier:           string;
    kind:           string;
    visible:        boolean;
    image:          string;
    nbr_of_success: number;
    users_url:      string;
    achievements:   any[];
    campus:         string[]
    parent:         null;
    title:          null;
}
